// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	auth3 "github.com/malikabdulaziz/tmn-backend/controllers/auth"
	"github.com/malikabdulaziz/tmn-backend/libs"
	"github.com/malikabdulaziz/tmn-backend/middlewares"
	"github.com/malikabdulaziz/tmn-backend/repositories/auth"
	"github.com/malikabdulaziz/tmn-backend/repositories/user"
	auth2 "github.com/malikabdulaziz/tmn-backend/services/auth"
)

// Injectors from wire.go:

func InitializeRouter() *httprouter.Router {
	validate := libs.NewValidator()
	repositoryAuthInterface := auth.NewRepositoryAuthJWTImpl()
	authMiddleware := middlewares.NewAuthMiddleware(validate, repositoryAuthInterface)
	loggingMiddleware := middlewares.NewLoggingMiddleware()
	db := libs.NewDatabase()
	repositoryUserInterface := user.NewRepositoryUserImpl()
	serviceAuthInterface := auth2.NewServiceAuthImpl(db, repositoryAuthInterface, repositoryUserInterface)
	controllerAuthInterface := auth3.NewControllerAuthImpl(db, serviceAuthInterface, repositoryUserInterface)
	router := libs.NewRouter(authMiddleware, loggingMiddleware, controllerAuthInterface)
	return router
}

// wire.go:

var authSet = wire.NewSet(auth.NewRepositoryAuthJWTImpl, user.NewRepositoryUserImpl, auth2.NewServiceAuthImpl, auth3.NewControllerAuthImpl)

var middlewareSet = wire.NewSet(middlewares.NewAuthMiddleware, middlewares.NewLoggingMiddleware)
