// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	auth3 "github.com/malikabdulaziz/tmn-backend/controllers/auth"
	building3 "github.com/malikabdulaziz/tmn-backend/controllers/building"
	buildingrestriction3 "github.com/malikabdulaziz/tmn-backend/controllers/buildingrestriction"
	dashboard3 "github.com/malikabdulaziz/tmn-backend/controllers/dashboard"
	"github.com/malikabdulaziz/tmn-backend/controllers/image"
	poi3 "github.com/malikabdulaziz/tmn-backend/controllers/poi"
	salespackage3 "github.com/malikabdulaziz/tmn-backend/controllers/salespackage"
	savedpolygon3 "github.com/malikabdulaziz/tmn-backend/controllers/savedpolygon"
	"github.com/malikabdulaziz/tmn-backend/libs"
	"github.com/malikabdulaziz/tmn-backend/middlewares"
	"github.com/malikabdulaziz/tmn-backend/repositories/auth"
	"github.com/malikabdulaziz/tmn-backend/repositories/building"
	"github.com/malikabdulaziz/tmn-backend/repositories/buildingrestriction"
	"github.com/malikabdulaziz/tmn-backend/repositories/dashboard"
	"github.com/malikabdulaziz/tmn-backend/repositories/poi"
	"github.com/malikabdulaziz/tmn-backend/repositories/salespackage"
	"github.com/malikabdulaziz/tmn-backend/repositories/savedpolygon"
	"github.com/malikabdulaziz/tmn-backend/repositories/user"
	"github.com/malikabdulaziz/tmn-backend/services/acquisition"
	auth2 "github.com/malikabdulaziz/tmn-backend/services/auth"
	building2 "github.com/malikabdulaziz/tmn-backend/services/building"
	"github.com/malikabdulaziz/tmn-backend/services/buildingproposal"
	buildingrestriction2 "github.com/malikabdulaziz/tmn-backend/services/buildingrestriction"
	dashboard2 "github.com/malikabdulaziz/tmn-backend/services/dashboard"
	"github.com/malikabdulaziz/tmn-backend/services/loi"
	poi2 "github.com/malikabdulaziz/tmn-backend/services/poi"
	salespackage2 "github.com/malikabdulaziz/tmn-backend/services/salespackage"
	savedpolygon2 "github.com/malikabdulaziz/tmn-backend/services/savedpolygon"
)

// Injectors from wire.go:

func InitializeRouter() *httprouter.Router {
	validate := libs.NewValidator()
	repositoryAuthInterface := auth.NewRepositoryAuthJWTImpl()
	authMiddleware := middlewares.NewAuthMiddleware(validate, repositoryAuthInterface)
	db := libs.NewDatabase()
	repositoryBuildingInterface := building.NewRepositoryBuildingImpl()
	buildingMiddleware := middlewares.NewBuildingMiddleware(validate, db, repositoryBuildingInterface)
	repositoryPOIInterface := poi.NewRepositoryPOIImpl()
	poiMiddleware := middlewares.NewPOIMiddleware(validate, db, repositoryPOIInterface)
	repositorySalesPackageInterface := salespackage.NewRepositorySalesPackageImpl()
	salesPackageMiddleware := middlewares.NewSalesPackageMiddleware(validate, db, repositorySalesPackageInterface)
	repositoryBuildingRestrictionInterface := buildingrestriction.NewRepositoryBuildingRestrictionImpl()
	buildingRestrictionMiddleware := middlewares.NewBuildingRestrictionMiddleware(validate, db, repositoryBuildingRestrictionInterface)
	repositorySavedPolygonInterface := savedpolygon.NewRepositorySavedPolygonImpl()
	savedPolygonMiddleware := middlewares.NewSavedPolygonMiddleware(validate, db, repositorySavedPolygonInterface)
	loggingMiddleware := middlewares.NewLoggingMiddleware()
	repositoryUserInterface := user.NewRepositoryUserImpl()
	serviceAuthInterface := auth2.NewServiceAuthImpl(db, repositoryAuthInterface, repositoryUserInterface)
	controllerAuthInterface := auth3.NewControllerAuthImpl(db, serviceAuthInterface, repositoryUserInterface)
	erpClient := libs.ProvideERPClient()
	logger := libs.NewLogger()
	serviceBuildingInterface := building2.NewServiceBuildingImpl(db, repositoryBuildingInterface, repositoryPOIInterface, erpClient, logger)
	controllerBuildingInterface := building3.NewControllerBuildingImpl(serviceBuildingInterface)
	controllerImageInterface := image.NewControllerImageImpl()
	servicePOIInterface := poi2.NewServicePOIImpl(db, repositoryPOIInterface)
	controllerPOIInterface := poi3.NewControllerPOIImpl(servicePOIInterface)
	serviceSalesPackageInterface := salespackage2.NewServiceSalesPackageImpl(db, repositorySalesPackageInterface, repositoryBuildingInterface)
	controllerSalesPackageInterface := salespackage3.NewControllerSalesPackageImpl(serviceSalesPackageInterface)
	serviceBuildingRestrictionInterface := buildingrestriction2.NewServiceBuildingRestrictionImpl(db, repositoryBuildingRestrictionInterface, repositoryBuildingInterface)
	controllerBuildingRestrictionInterface := buildingrestriction3.NewControllerBuildingRestrictionImpl(serviceBuildingRestrictionInterface)
	serviceSavedPolygonInterface := savedpolygon2.NewServiceSavedPolygonImpl(db, repositorySavedPolygonInterface)
	controllerSavedPolygonInterface := savedpolygon3.NewControllerSavedPolygonImpl(serviceSavedPolygonInterface)
	repositoryDashboardInterface := dashboard.NewRepositoryDashboardImpl()
	serviceDashboardInterface := dashboard2.NewServiceDashboardImpl(db, repositoryDashboardInterface, logger)
	controllerDashboardInterface := dashboard3.NewControllerDashboardImpl(serviceDashboardInterface)
	router := libs.NewRouter(authMiddleware, buildingMiddleware, poiMiddleware, salesPackageMiddleware, buildingRestrictionMiddleware, savedPolygonMiddleware, loggingMiddleware, controllerAuthInterface, controllerBuildingInterface, controllerImageInterface, controllerPOIInterface, controllerSalesPackageInterface, controllerBuildingRestrictionInterface, controllerSavedPolygonInterface, controllerDashboardInterface)
	return router
}

func InitializeBuildingService() building2.ServiceBuildingInterface {
	db := libs.NewDatabase()
	repositoryBuildingInterface := building.NewRepositoryBuildingImpl()
	repositoryPOIInterface := poi.NewRepositoryPOIImpl()
	erpClient := libs.ProvideERPClient()
	logger := libs.NewLogger()
	serviceBuildingInterface := building2.NewServiceBuildingImpl(db, repositoryBuildingInterface, repositoryPOIInterface, erpClient, logger)
	return serviceBuildingInterface
}

func InitializeAcquisitionService() acquisition.ServiceAcquisitionInterface {
	db := libs.NewDatabase()
	erpClient := libs.ProvideERPClient()
	logger := libs.NewLogger()
	serviceAcquisitionInterface := acquisition.NewServiceAcquisitionImpl(db, erpClient, logger)
	return serviceAcquisitionInterface
}

func InitializeBuildingProposalService() buildingproposal.ServiceBuildingProposalInterface {
	db := libs.NewDatabase()
	erpClient := libs.ProvideERPClient()
	logger := libs.NewLogger()
	serviceBuildingProposalInterface := buildingproposal.NewServiceBuildingProposalImpl(db, erpClient, logger)
	return serviceBuildingProposalInterface
}

func InitializeLOIService() loi.ServiceLOIInterface {
	db := libs.NewDatabase()
	erpClient := libs.ProvideERPClient()
	logger := libs.NewLogger()
	serviceLOIInterface := loi.NewServiceLOIImpl(db, erpClient, logger)
	return serviceLOIInterface
}

// wire.go:

var authSet = wire.NewSet(auth.NewRepositoryAuthJWTImpl, user.NewRepositoryUserImpl, auth2.NewServiceAuthImpl, auth3.NewControllerAuthImpl)

var buildingSet = wire.NewSet(building.NewRepositoryBuildingImpl, building2.NewServiceBuildingImpl, building3.NewControllerBuildingImpl)

var imageSet = wire.NewSet(image.NewControllerImageImpl)

var poiSet = wire.NewSet(poi.NewRepositoryPOIImpl, poi2.NewServicePOIImpl, poi3.NewControllerPOIImpl)

var salespackageSet = wire.NewSet(salespackage.NewRepositorySalesPackageImpl, salespackage2.NewServiceSalesPackageImpl, salespackage3.NewControllerSalesPackageImpl)

var buildingrestrictionSet = wire.NewSet(buildingrestriction.NewRepositoryBuildingRestrictionImpl, buildingrestriction2.NewServiceBuildingRestrictionImpl, buildingrestriction3.NewControllerBuildingRestrictionImpl)

var savedpolygonSet = wire.NewSet(savedpolygon.NewRepositorySavedPolygonImpl, savedpolygon2.NewServiceSavedPolygonImpl, savedpolygon3.NewControllerSavedPolygonImpl)

var dashboardSet = wire.NewSet(dashboard.NewRepositoryDashboardImpl, dashboard2.NewServiceDashboardImpl, dashboard3.NewControllerDashboardImpl)

var middlewareSet = wire.NewSet(middlewares.NewAuthMiddleware, middlewares.NewBuildingMiddleware, middlewares.NewPOIMiddleware, middlewares.NewSalesPackageMiddleware, middlewares.NewBuildingRestrictionMiddleware, middlewares.NewSavedPolygonMiddleware, middlewares.NewLoggingMiddleware)
